ui_print "- Clearing old fdr_check"
#This file will be automatically generated by system after reboot
rm /data/vendor/modem_fdr/fdr_check
REPLACE="
/system/vendor/rfs/msm/mpss/readonly/vendor/mbn/mcfg_sw/
"